#!/usr/bin/env python3
"""Terminal-style profile banner: 'profile.sh --live'.
Left panel is a halftone dot-matrix render of the GitHub avatar (no external
avatar-to-ascii service — computed locally with PIL/numpy). Right panel is a
static SYSTEM.INFO block. Outputs light/dark SVG variants to ../../assets/.

Regenerate: python3 scripts/banner/generate.py
This is a design asset (not auto-regenerated by a workflow) — rerun by hand
after changing avatar.png or the INFO fields below.
"""
from pathlib import Path
from xml.sax.saxutils import escape

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
ASSETS = HERE.parent.parent / "assets"
AVATAR = HERE / "avatar.png"

GRID = 30  # dot-matrix resolution (GRID x GRID cells)
CELL = 8   # px per cell
PAD = 20

INFO = [
    ("Subject", "Federico D'Orsi"),
    ("Role", "Builder — AI systems & automation"),
    ("Founded", "DirtyTag"),
    ("Focus", "Agents · Automation · Resale"),
    ("Toolchain", "Claude Code · n8n"),
    ("Core.Lang", "Python · JavaScript"),
    ("Core.Data", "Airtable"),
    ("Grid.Instagram", "@DIRTY_TAG"),
    ("Grid.GitHub", "FedericoLuigiDOrsi"),
]


def halftone_dots():
    im = Image.open(AVATAR).convert("L").resize((GRID, GRID), Image.LANCZOS)
    arr = np.asarray(im).astype(float) / 255.0
    dots = []
    for y in range(GRID):
        for x in range(GRID):
            darkness = 1.0 - arr[y, x]
            if darkness < 0.12:
                continue
            r = (CELL / 2) * min(darkness * 1.15, 1.0)
            cx = PAD + x * CELL + CELL / 2
            cy = PAD + y * CELL + CELL / 2
            dots.append((cx, cy, round(r, 2)))
    return dots


def render(dark: bool) -> str:
    bg = "#0d1117" if dark else "#ffffff"
    panel = "#161b22" if dark else "#f6f8fa"
    border = "#30363d" if dark else "#d0d7de"
    fg = "#c9d1d9" if dark else "#24292f"
    dim = "#8b949e" if dark else "#57606a"
    accent = "#58a6ff" if dark else "#2E9EF7"
    dot_color = "#c9d1d9" if dark else "#24292f"

    map_size = PAD * 2 + GRID * CELL
    width = 880
    height = map_size + 64
    info_x = map_size + 40

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" font-family="Fira Code, Consolas, monospace">',
        f'<rect width="{width}" height="{height}" rx="12" fill="{bg}"/>',
        f'<rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="12" fill="none" stroke="{border}"/>',
        # title bar
        f'<rect x="0.5" y="0.5" width="{width - 1}" height="34" rx="12" fill="{panel}"/>',
        f'<rect x="0.5" y="22" width="{width - 1}" height="13" fill="{panel}"/>',
        f'<line x1="0.5" y1="34.5" x2="{width - 0.5}" y2="34.5" stroke="{border}"/>',
        '<circle cx="20" cy="17" r="5" fill="#ff5f56"/>',
        '<circle cx="38" cy="17" r="5" fill="#ffbd2e"/>',
        '<circle cx="56" cy="17" r="5" fill="#27c93f"/>',
        f'<text x="{width / 2}" y="21" font-size="12" fill="{dim}" text-anchor="middle">profile.sh --live</text>',
        # visual.map panel
        f'<text x="{PAD}" y="{34 + 22}" font-size="11" fill="{accent}" letter-spacing="1">VISUAL.MAP</text>',
        f'<rect x="{PAD - 4}" y="{34 + 30}" width="{map_size - 2 * PAD + 8}" height="{map_size - 8}" rx="6" fill="{panel}" stroke="{border}"/>',
    ]

    y_off = 34 + 30
    for cx, cy, r in halftone_dots():
        parts.append(f'<circle cx="{cx:.1f}" cy="{cy + y_off:.1f}" r="{r}" fill="{dot_color}"/>')

    # system.info panel
    parts.append(f'<text x="{info_x}" y="{34 + 22}" font-size="11" fill="{accent}" letter-spacing="1">SYSTEM.INFO</text>')
    ty = 34 + 46
    for label, value in INFO:
        parts.append(f'<text x="{info_x}" y="{ty}" font-size="12.5" fill="{dim}">{escape(label)}</text>')
        parts.append(f'<text x="{width - PAD}" y="{ty}" font-size="12.5" fill="{fg}" text-anchor="end">{escape(value)}</text>')
        ty += 24

    # status line
    parts.append(f'<line x1="{PAD}" y1="{height - 26}" x2="{width - PAD}" y2="{height - 26}" stroke="{border}"/>')
    parts.append(f'<circle cx="{PAD + 4}" cy="{height - 12}" r="3" fill="#27c93f"/>')
    parts.append(f'<text x="{PAD + 14}" y="{height - 8}" font-size="11" fill="{dim}">ALL SYSTEMS NOMINAL</text>')
    parts.append(f'<text x="{width - PAD}" y="{height - 8}" font-size="11" fill="{dim}" text-anchor="end">FedericoLuigiDOrsi</text>')

    parts.append("</svg>")
    return "\n".join(parts)


def main():
    ASSETS.mkdir(exist_ok=True)
    (ASSETS / "banner-dark.svg").write_text(render(dark=True))
    (ASSETS / "banner-light.svg").write_text(render(dark=False))
    print("wrote banner-dark.svg and banner-light.svg")


if __name__ == "__main__":
    main()
